// <auto-generated />
using System;
using MeowWorld.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeowWorld.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616070717_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MeowWorld.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            Breed = "Scottish Fold",
                            CreatedAt = new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "おっとりした性格の猫",
                            Name = "Momo"
                        },
                        new
                        {
                            Id = 2,
                            Age = 4,
                            Breed = "Maine Coon",
                            CreatedAt = new DateTime(2026, 1, 11, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "大きくて人懐っこい猫",
                            Name = "Sora"
                        },
                        new
                        {
                            Id = 3,
                            Age = 1,
                            Breed = "Munchkin",
                            CreatedAt = new DateTime(2026, 1, 12, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "短い足がチャームポイント",
                            Name = "Hana"
                        },
                        new
                        {
                            Id = 4,
                            Age = 6,
                            Breed = "Bombay",
                            CreatedAt = new DateTime(2026, 1, 13, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "つやのある黒毛の猫",
                            Name = "Kuro"
                        },
                        new
                        {
                            Id = 5,
                            Age = 3,
                            Breed = "Ragdoll",
                            CreatedAt = new DateTime(2026, 1, 14, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            Description = "穏やかで抱っこ好きな猫",
                            Name = "Yuki"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
